title: GA4GH - DUO
label: GA4GH::DUO
email: ga4gh-data-use-subgroup@ga4gh.org
github_organisation: ebispot
future: true
navigation_categories:
  news: News
  documentation: Documentation
  howto: Examples & Guides
navigation_static_links:
  ga4gh:
    url: "http://ga4gh.org"
    label: "GA4GH Main Site"
  ga4gh-gks:
    url: "http://ga4gh-gks.github.io"
    label: "GA4GH::GKS"
  ga4gh-metadata:
    url: "http://ga4gh-metadata.github.io"
    label: "GA4GH::Metadata"
  ga4gh-lsg:
    url: "https://github.com/ga4gh/large-scale-genomics-wiki/wiki/"
    label: "GA4GH Large Scale Genomics"   
  ga4gh-github:
    url: "https://github.com/ga4gh/"
    label: "GA4GH Github Projects"
